### ISSUE TITLE
Can't work on AndroidStudio3.0

### ISSUE THREAD

**Issue by crazecoder** [siosio/GradleDependenciesHelperPlugin#10]

**Comment by thiagotalma** [comment]
@siosio any news here?

**Comment by siosio** [comment]
I confirmed it in Android Studio, but it works.
As version 1.10 or higher is not supported, please install 1.9.
This plugin works with Smart Completion (Ctrl + Shift + Space), not Basic Completion (Ctrl + Space).

**Comment by crazecoder** [comment]
How do I customize shortcut keys?
