### ISSUE TITLE
gradle other completion except 'Maven  Dependency', like 'build.gradle syntax completion'

### ISSUE THREAD

**Issue by zhanggang807** [siosio/GradleDependenciesHelperPlugin#14]
gradle other completion except 'Maven  Dependency', like 'build.gradle syntax completion'

**Comment by siosio** [comment]
Can complement build.gradle with IntelliJ.

For example, candidates are displayed as follows.
![image](https://user-images.githubusercontent.com/1200731/49317308-4b4acd80-f537-11e8-822f-39311b60db03.png)
