### ISSUE TITLE
Does not work behind proxy!

### ISSUE THREAD

**Issue by aadrian** [siosio/GradleDependenciesHelperPlugin#15]
The latest version of this plug-in, with the latest version of IntelliJ does not seem to work behind proxies (protected with user and password): "No Suggestions" is displayed for any artifact.

The issue seems to be for proxies with username and passwords: even if IntelliJ is configured correctly and works behind these proxies, this plug-in does not seem to work :( .

Is there any log that can be activated to give you more information?

Thank you.

**Comment by siosio** [comment]
Thanks for the bug report.

fix commit: 24979e76
