### ISSUE TITLE
This plug-in prevents pasting in gradle files for IU-143.1015.7

### ISSUE THREAD

**Issue by aadrian** [siosio/GradleDependenciesHelperPlugin#2]
When this plug-in is active, with the last IntelliJ version (as of now) : IU-143.1015.7 it's not possible to paste in the Gradle build files anymore :(.

If I deactivate this plug-in, than I can paste again in the Gradle file.

This happens on Win8 + mentioned IntelliJ version.

**Comment by siosio** [comment]
Because there is no Windows8 environment, you can not see the problem.

In the following OS, there is no problem.
- Win7
- Mac

**Comment by aadrian** [comment]
@siosio This happens on Win10 too.
Also in the latest IntelliJ version (not just the one initially mentioned)

**Comment by aadrian** [comment]
Starting with IU-2017.1 this behavior can't be reproduced anymore.
