### ISSUE TITLE
Plugin "Gradle Dependencies Helper" was not loaded

### ISSUE THREAD

**Issue by zeeshanaslam78** [siosio/GradleDependenciesHelperPlugin#3]
I updated Android Studio to 2.0 and starts getting this error
Now I have Android Studio Version 2.0 Preview 6
**Plugin Error
Problems found loading plugins:
Plugin "Gradle Dependencies Helper" was not loaded: required plugin "org.jetbrains.idea.maven" not installed.
 Disable Gradle Dependencies Helper
Open plugin manager**

I disabled plugin and when I try to enable again it says

**Can not save settings
Unable to apply changes Plugin "Gradle Dependencies Helper" won't be able to load**

I also reinstalled but getting same error.

I want to tell you one thing that I changed info.plist file of android studio
_Android Studio -> Show Package Contents -> Contents -> info.plist_

So error is due to this or some other thing 

Any idea

**Comment by siosio** [comment]
Tank you for the reporting the issue. Released a bug fix version(1.7).

download page -> https://plugins.jetbrains.com/plugin/7299

**Comment by zeeshanaslam78** [comment]
Thank you so much for your reply and fixing this bug. You are very nice person
